---

  - name: Update APT index
    apt: update_cache=yes

  - name: Install PostgreSQL APT packages
    apt: pkg={{item}} state=latest
    with_items:
    - postgresql-{{postgres.version}}
    - postgresql-contrib-{{postgres.version}}
    - libpq-dev
 
  - name: Install PostGIS APT packages
    apt: pkg={{item}} state=latest
    with_items:
    - postgresql-{{postgres.version}}-postgis-{{postgis.version}}
    when: postgis.version
  
  - name: Install auxiliary packages
    apt: pkg={{item}} state=latest
    with_items:
    - htop

  - name: Download pgtune script
    get_url: 
      url: https://github.com/iterativo-git/pgtune/raw/iterativo-tune/pgtune
      dest: /usr/local/bin/pgtune
      mode: '0755'

  - file: path=/usr/local/share/pgtune state=directory
  - name: Download pgtune settings
    get_url:
      url: https://github.com/iterativo-git/pgtune/raw/iterativo-tune/pg_settings-{{postgres.version}}-64
      dest: /usr/local/share/pgtune/pg_settings-{{postgres.version}}-64
      mode: '0644'
