---

 #- debug: var=postgres
  
  - include: install-packages.yml
    tags: install
  
  #
  # Compute facts
  #

  - service: name=postgresql.service state=started

  - include: compute-facts.yml
  
  #
  # Configure service 
  #

  - service: name=postgresql.service state=stopped
  
  - service: name=rsync.service state=stopped
  
  - include: configure-service.yml
    tags: configure

  - include: configure-archive-export.yml
    when: replication.role == 'master'
    tags: configure
 
  - include: configure-archive-import.yml
    when: replication.role == 'standby'
    tags: configure
 
  - service: name=postgresql.service enabled=yes state=started
  - service: name=postgresql@{{postgres.version}}-main.service state=started
  
  - service: name=rsync.service state=started enabled=yes
  
  #
  # Create tablespaces
  #

  - include: create-tablespaces.yml
    tags: setup

  #
  # Setup users and databases (master)
  #

  - include: create-users.yml
    when: not (replication.role == 'standby')
    tags: setup
  
  - include: create-databases.yml
    when: not (replication.role == 'standby')
    tags: setup
  
  #
  # Take and apply basebackup from master (standby)
  #

  - service: name=postgresql.service state=stopped
    when: replication.role == 'standby'
    tags: basebackup
  
  - include: basebackup-master.yml
    when: replication.role == 'standby'
    tags: basebackup
  
  - service: name=postgresql.service state=started
    when: replication.role == 'standby'
    tags: basebackup

  #
  # Install helper scripts
  #
  
  - include: install-helper-scripts.yml

